select ID, coalesce(nullif(fam,''), '-')::varchar fam, coalesce(nullif(im,''), '-')::varchar im, coalesce(nullif(ot,''), '-')::varchar ot, DR, W, DDEATH, DOCTYPE, DOCSER, DOCNUM, DOCDATE, NAME_VP, ERP, IDIDEAD
, SOURCE, IDLOGLOAD, IDLOGSEND, COMMENTARY, GOSR, SUBGOSR, RAYONR, GORODR, NAMENPR
, GOSL, SUBGOSL, RAYONL, GORODL, NAMENPL, STREETL, HOUSEL, KORPL, FLATL
, NUMAZSM, DATEAZSM, SERSV, NUMSV, DOSTRDS, DOSTRDR, DOCNAME, DDEATHZAGS, STATUSCODE, DATESEND
, STATUSDBEG, COMMCHANGE, DATECHANGE, ORGAN_CONFIRM, DATE_CONFIRM, NUM_CONFIRM, NAME_CONFIRM
, CODE_CONFIRM, CODEZAGS, CODESUBGOSL, INDEXL, AOIDL, ADDRESSR, CODE_VP, REASON, OKSM
, CREATEDATE
from public.idead