select IDROW, TYPEROW, DOCTYPE, DOCSER, DOCNUM, DOCDATE, DOCEXP, NAME_VP
, INN, WINN, WNAME, WPHONE, DCROSS
, null NUMAZ, null DATEAZ, IPRESENTER_IDRW, DOC_OKSM
, DOCDIVISION, source
, IDRW
, CREATEDATE ---новое поле
from public.idoc
