    SELECT mo, MO modoc, 1 doctype, ACCNO, ACCDT, 0 STEPEXP, NULL schetnrec, TYPECONT, CONT, (APPBASE + APPUPKEEP + KSSBASE + KSSUPKEEP + SMPBASE + SMPUPKEEP + SZPBASE + SZPUPKEEP)  sumcheck, (KSSBASE + KSSUPKEEP)  SUMKSS, (SZPBASE + SZPUPKEEP)  SUMSZP, (APPBASE + APPUPKEEP)  SUMAPP, (SMPBASE + SMPUPKEEP)  SUMSMP, (APPCOUNT + KSSCOUNT + SMPCOUNT + SZPCOUNT)  COUNTCHECK, YEAR, MONTH, idrw, LASTUPDATE, UPDT createdate, NULL SVODDT, NULL MEDCHECK_IDRW, NULL buhdt, NULL SCHETTYPE
    FROM MEDCHECK m WHERE accdt >= TO_DATE('2020-01-01', 'YYYY-MM-DD')
UNION ALL
    SELECT  m.mo, m.mo modoc, 2 doctype, m.DOCEXP ACCNO, m.DOCEXPDT ACCDT, m.STEPEXP, NULL schetnrec, m.TYPECONT, m.CONT, SUM(m.RECLBASE + m.RECLUPKEEP) sumcheck, SUM(DECODE(m.usl_ok, 1, m.RECLBASE + m.RECLUPKEEP, 0)) SUMKSS, SUM(DECODE(m.usl_ok, 2, m.RECLBASE + m.RECLUPKEEP, 0)) SUMSZP, SUM(DECODE(m.usl_ok, 3, m.RECLBASE + m.RECLUPKEEP, 0)) SUMAPP, SUM(DECODE(m.usl_ok, 4, m.RECLBASE + m.RECLUPKEEP, 0)) SUMSMP, COUNT(*) COUNTCHECK, m.YEAR, m.MONTH, MAX(m.idrw) idrw, MAX(m.LASTUPDATE) LASTUPDATE, MAX(m.docexpdt) createate, CASE WHEN m.STEPEXP = 1 THEN MAX(m.SVODDT) ELSE NULL END AS SVODDT, MAX(CASE WHEN m.STEPEXP = 1 THEN mc.IDRW ELSE NULL END) AS MEDCHECK_IDRW, NULL buhdt, NULL SCHETTYPE
    FROM EXPMED m
    LEFT JOIN MEDCHECK mc ON m.MO = mc.MO AND m.ACCNO = mc.ACCNO AND m.ACCDT = mc.ACCDT
    WHERE m.docexpdt >= TO_DATE('2020-01-01', 'YYYY-MM-DD') AND (m.stepexp = 1 AND m.ordnum IS NULL OR m.stepexp <> 1 AND m.typecont = DECODE(m.typemaker,5,4,m.typemaker)) AND (m.typemaker IN (4, 5) AND m.typeexp IN (1, 2) OR m.typemaker = 2)
    GROUP BY m.mo, m.DOCEXP, m.DOCEXPDT, m.STEPEXP, m.TYPECONT, m.CONT, m.YEAR, m.MONTH
UNION ALL
    SELECT m.mo, m.mo modoc, 3 doctype, DOCEXP ACCNO, DOCEXPDT ACCDT, STEPEXP, NULL schetnrec, TYPEMAKER TYPECONT, MAKER CONT, SUM(RECLBASE + RECLUPKEEP)   sumcheck, SUM(DECODE(usl_ok, 1, RECLBASE + RECLUPKEEP, 0))  SUMKSS, SUM(DECODE(usl_ok, 2, RECLBASE + RECLUPKEEP, 0))  SUMSZP, SUM(DECODE(usl_ok, 3, RECLBASE + RECLUPKEEP, 0))  SUMAPP, SUM(DECODE(usl_ok, 4, RECLBASE + RECLUPKEEP, 0))  SUMSMP, (COUNT(*))  COUNTCHECK, m.YEAR, m.MONTH, max(m.idrw) idrw, max(m.LASTUPDATE) LASTUPDATE, max(docexpdt) createate,  CASE WHEN m.STEPEXP = 1 THEN MAX(m.SVODDT) ELSE NULL END AS SVODDT, MAX(CASE WHEN m.STEPEXP = 1 THEN mc.IDRW ELSE NULL END) AS MEDCHECK_IDRW, NULL buhdt, NULL SCHETTYPE
    FROM EXPMED m
    LEFT JOIN MEDCHECK mc ON m.MO = mc.MO AND m.ACCNO = mc.ACCNO AND m.ACCDT = mc.ACCDT
    WHERE docexpdt >= TO_DATE('2020-01-01', 'YYYY-MM-DD') AND reclbase + reclupkeep <> 0 AND (stepexp = 1 AND ordnum IS NOT NULL OR stepexp <> 1) AND m.typecont = 2 AND typemaker IN (4, 5) AND typeexp IN (1, 2)
    GROUP BY m.mo, DOCEXP, DOCEXPDT, STEPEXP, TYPEMAKER, MAKER, m.YEAR, m.MONTH
UNION ALL
    SELECT m.mo, m.mo modoc, 4 doctype, DOCPENALTY ACCNO, DOCPENALTYDT ACCDT, STEPEXP, NULL schetnrec, TYPEMAKER TYPECONT, MAKER CONT, SUM(PENALTY) sumcheck, SUM(DECODE(USL_OK, 1, PENALTY, 0)) SUMKSS, SUM(DECODE(USL_OK, 2, PENALTY, 0)) SUMSZP, SUM(DECODE(USL_OK, 3, PENALTY, 0)) SUMAPP, SUM(DECODE(USL_OK, 4, PENALTY, 0)) SUMSMP, (COUNT(*))  COUNTCHECK, m.YEAR, m.MONTH, max(m.idrw) idrw, max(m.LASTUPDATE) LASTUPDATE, max(DOCPENALTYDT) createate, CASE WHEN m.STEPEXP = 1 THEN MAX(m.SVODDT) ELSE NULL END AS SVODDT, MAX(CASE WHEN m.STEPEXP = 1 THEN mc.IDRW ELSE NULL END) AS MEDCHECK_IDRW, NULL buhdt, NULL SCHETTYPE
    FROM EXPMED m
    LEFT JOIN MEDCHECK mc ON m.MO = mc.MO AND m.ACCNO = mc.ACCNO AND m.ACCDT = mc.ACCDT
    WHERE DOCPENALTYDT >= TO_DATE('2020-01-01', 'YYYY-MM-DD') AND PENALTY <> 0 AND (typemaker IN (4, 5) AND TYPEEXP IN (1, 2) OR TYPEMAKER = 2)
    GROUP BY m.mo, DOCPENALTY, DOCPENALTYDT, STEPEXP, TYPEMAKER, MAKER, m.YEAR, m.MONTH
UNION ALL
    SELECT mo, mo modoc, 5 doctype, accno, accdt, 0 stepexp, NULL schetnrec, typecont, cont, SUMPAY sumcheck, 0 sumkss, 0 sumszp, DECODE(typehelp,3,SUMPAY,0) sumapp, 0 sumsmp, 0 countcheck, YEAR, MONTH, id, lastupdate, TO_DATE(YEAR||'-01-01','YYYY-MM-DD') createdate, NULL SVODDT, NULL MEDCHECK_IDRW, NULL buhdt, NULL SCHETTYPE
    FROM PODCHECK JOIN SPMUMAIN sm ON PODCHECK.mo = SM.Code
    WHERE typehelp = 3 AND accdt>=TO_DATE('2020-01-01','YYYY-MM-DD') AND SUMPAY >0
UNION ALL
    SELECT mo, mo modoc, 6 doctype, accno, accdt, 0 stepexp, NULL schetnrec, typecont, cont, SUMPAY sumcheck, 0 sumkss, 0 sumszp, 0 sumapp, DECODE(TYPEHELP, 4, sumpay, 0)  sumsmp, 0 countcheck, YEAR, MONTH, id, lastupdate, TO_DATE(YEAR||'-01-01','YYYY-MM-DD') createdate, NULL SVODDT, NULL MEDCHECK_IDRW, NULL buhdt, NULL SCHETTYPE
	FROM PODCHECK
	WHERE typehelp = 4 AND accdt>=TO_DATE('2020-01-01','YYYY-MM-DD') AND SUMPAY >0 AND TO_DATE(YEAR||'-'||LPAD(MONTH, 2, 0)||'-01', 'YYYY-MM-DD') >=TO_DATE('2024-08-01', 'YYYY-MM-DD')
	UNION ALL
	SELECT mo, mo modoc, 6 doctype, null accno, NULL accdt, 0 stepexp, NULL schetnrec, typecont, cont, SUMNORM sumcheck, 0 sumkss, 0 sumszp, 0 sumapp, SUMNORM sumsmp, 0 countcheck, YEAR, MONTH, idrw id, lastupdate, TO_DATE(YEAR||'-01-01','YYYY-MM-DD') createdate, NULL SVODDT, NULL MEDCHECK_IDRW, NULL buhdt, NULL SCHETTYPE
	FROM SPPODNORM
	WHERE TO_DATE(YEAR||'-'||LPAD(MONTH, 2, 0)||'-01', 'YYYY-MM-DD') BETWEEN TO_DATE('2020-01-01', 'YYYY-MM-DD') AND TO_DATE('2024-07-01', 'YYYY-MM-DD') AND SUMNORM > 0 AND typehelp = 4
UNION ALL
    SELECT mo, mo modoc, 7 doctype, ACCNO, ACCDT, 0 STEPEXP, NULL schetnrec, 2 TYPECONT, c.smo CONT, sumprep sumcheck, 0 SUMKSS, 0 SUMSZP, 0 SUMAPP, 0 SUMSMP, 0 COUNTCHECK, c.YEAR, c.MONTH, c.id idrw, c.LASTUPDATE, REQDT createdate, NULL SVODDT, NULL MEDCHECK_IDRW, NULL buhdt, NULL SCHETTYPE
    FROM REQPREPMO c
    INNER JOIN REQPREPSMO s ON s.ID = c.ID_REQPREPSMO
    WHERE ACCDT  >= TO_DATE('2023-01-01', 'YYYY-MM-DD') AND s.DIRDT IS NOT NULL
UNION ALL
    SELECT 1 mo, 1 modoc, 8 doctype, nschet ACCNO, dschet ACCDT, NULL STEPEXP, schetnrec, 6  TYPECONT, tf CONT, summap sumcheck, 0 SUMKSS, 0 SUMSZP, 0 SUMAPP, 0 SUMSMP, 0 COUNTCHECK, YEAR, MONTH, idrw, LASTUPDATE, dschet createdate, NULL SVODDT, NULL MEDCHECK_IDRW, NULL buhdt, SCHETTYPE
    FROM TFOUTSCHET WHERE dschet >= TO_DATE('2020-01-01', 'YYYY-MM-DD')
UNION ALL
    SELECT 1 mo, 1 modoc, 9 doctype, nschet ACCNO, dschet ACCDT, NULL STEPEXP, schetnrec, 6  TYPECONT, tf CONT, summap sumcheck, 0 SUMKSS, 0 SUMSZP, 0 SUMAPP, 0 SUMSMP, 0 COUNTCHECK, YEAR, MONTH, idrw, LASTUPDATE, dschet createdate, NULL SVODDT, NULL MEDCHECK_IDRW, buhdt, SCHETTYPE
    FROM TFINSCHET WHERE  dschet >= TO_DATE('2020-01-01', 'YYYY-MM-DD')
