SELECT c.COLUMN_NAME, c.DATA_TYPE, c.DATA_SCALE,
       CASE WHEN pk.CONSTRAINT_TYPE = 'P' THEN 'Primary Key' ELSE '' END AS IS_PRIMARY_KEY
FROM ALL_TAB_COLUMNS c
LEFT JOIN (
    SELECT cc.TABLE_NAME, cc.COLUMN_NAME, cons.CONSTRAINT_TYPE
    FROM ALL_CONS_COLUMNS cc
    JOIN ALL_CONSTRAINTS cons ON cc.CONSTRAINT_NAME = cons.CONSTRAINT_NAME
    WHERE cons.CONSTRAINT_TYPE = 'P'
) pk ON c.TABLE_NAME = pk.TABLE_NAME AND c.COLUMN_NAME = pk.COLUMN_NAME
WHERE c.TABLE_NAME = :TABLENAME
ORDER BY c.COLUMN_NAME
