INSERT INTO KOKNAEV.SPACC
(FIL, TYPECONT, CONT, BANKACC, NAMEACC, NAMEBANK, ACCOUNT, BIC, CORRACC, NAMEEXT, INN, KPP, KBK, PREFNOTE, LS)
VALUES(:s, :s, :s, :s, :s, :s, :s, :s, :s, :s, :s, :s, :s, :s, :s)
