INSERT INTO KOKNAEV.SPPAYACC
(CODE, NAMEPAY, BANKACC, PORDER, WAYFORMPD, WAYFORMEPD, NA1, NA3, TYPECONT, DETOBJECT, KBK, PAYERSTAT, PRIM, PACC, PKAU, DBEGIN, DEND, PTYPEADDCONT, KBKUFK, KOSGU, PAVANS, KAU, NAME, KBKDOPNAME)
VALUES(:s, :s, :s, :s, :s, :s, :s, :s, :s, :s, :s, :s, :s, :s, :s, :s, :s, :s, :s, :s, :s, :s, :s, :s)
