INSERT INTO SPEINDEX (CODE, NAME, EINDEXFORM, TYPEINDEX, INTONLY, EI, PERIOD, INTOTEMO, KOSGU, FSUM, FORMULA, FILEDNAME, NUMBORD, SIGNEXT)
VALUES (:1, :2, :3, :4, :5, :6, :7, :8, :9, :10, :11, :12, :13, :14)
